sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/*.pyc,**/site-packages/**,GenAI_Part/venv/**,tests/**,**/*.pdf,coverage.xml,**/.pytest_cache/**
sonar.python.coverage.reportPaths=GenAI_Part/coverage.xml
