####################################################
# DATABASE CONFIGURATION
####################################################

# Database Configuration
spring.datasource.url=jdbc:postgresql://contract-negotiation-db.cn62i4ggemap.ap-south-1.rds.amazonaws.com:5432/contractnegotiationdb
spring.datasource.username=postgres
spring.datasource.password=contract334
spring.datasource.driver-class-name=org.postgresql.Driver
####################################################
# JPA / HIBERNATE
####################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

####################################################
# SERVER
####################################################

server.port=8080

####################################################
# JWT
####################################################

app.jwt.secret=9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d
app.jwt.expiration-ms=86400000

####################################################
# LOGGING
####################################################

logging.level.org.springframework.security=INFO
logging.level.com.softwarecontract.backend=DEBUG

####################################################
# AWS S3
####################################################

aws.s3.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.s3.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.s3.bucket-name=contract-negotiation-system-docs
aws.s3.endpoint=${AWS_S3_ENDPOINT:}

####################################################
# FASTAPI GENAI
####################################################

fastapi.negotiate.url=https://contract-negotiation-system.onrender.com/api/negotiate
app.fastapi.connect-timeout-ms=${FASTAPI_CONNECT_TIMEOUT_MS:10000}
app.fastapi.read-timeout-ms=${FASTAPI_READ_TIMEOUT_MS:90000}
app.fastapi.max-retries=${FASTAPI_MAX_RETRIES:3}
app.fastapi.retry-delay-ms=${FASTAPI_RETRY_DELAY_MS:2000}
openai.api.key=${OPENAI_API_KEY}