sonar.projectKey=genai-project
sonar.projectName=genai-project
sonar.sources=.
sonar.python.version=3.9
sonar.exclusions=**/*.pdf,pytest_failures.log,pytest_failures_utf8.txt,pytest_coverage_term.txt,venv/**,**/venv/**,**/.pytest_cache/**,**/__pycache__/**,coverage.xml,tests/**,**/.env/**,**/test_stdout_utf8.txt,**/run_tests_helper.py
sonar.python.coverage.reportPaths=coverage.xml
