sonar.projectKey=genai-project
sonar.projectName=genai-project
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=tests/**, **/*.pdf, pytest_failures.log, pytest_failures_utf8.txt, pytest_coverage_term.txt
sonar.python.coverage.reportPaths=coverage.xml
