sonar.projectKey=genai-project
sonar.projectName=genai-project
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=tests/**, **/*.pdf, pytest_failures.log, pytest_failures_utf8.txt, pytest_coverage_term.txt, venv/**, **/venv/**, **/.pytest_cache/**, **/__pycache__/**, coverage.xml, **/.env/**, **/test_stdout_utf8.txt, **/run_tests_helper.py
sonar.python.coverage.reportPaths=coverage.xml
